run csa directly, no docker image / deprecate verbose

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,24 +57,75 @@ inputs:
     description: "The target to scan. Should be a docker image name or a path to a directory containing a Dockerfile."
     required: true
   verbose:
-    description: "Enable verbose logging."
+    description: 'DEPRECATED - parameter has no effect. Set log_level to DEBUG for the same effect.'
     required: false
+  image_tag:
+    description: 'The soosio/csa image tag to use; defaults to latest'
+    required: false
+    default: 'latest'
+
 runs:
-  using: "docker"
-  image: "Dockerfile"
-  env:
-    SOOS_API_KEY: ${{ inputs.api_key }}
-    SOOS_API_URL: ${{ inputs.api_url }}
-    SOOS_BRANCH_NAME: ${{ inputs.branch_name }}
-    SOOS_BRANCH_URI: ${{ inputs.branch_uri }}
-    SOOS_BUILD_URI: ${{ inputs.build_uri }}
-    SOOS_BUILD_VERSION: ${{ inputs.build_version }}
-    SOOS_CLIENT_ID: ${{ inputs.client_id }}
-    SOOS_LOG_LEVEL: ${{ inputs.log_level }}
-    SOOS_ON_FAILURE: ${{ inputs.on_failure }}
-    SOOS_OPERATING_ENVIRONMENT: ${{ inputs.operating_environment }}
-    SOOS_OTHER_OPTIONS: ${{ inputs.other_options }}
-    SOOS_OUTPUT_FORMAT: ${{ inputs.output_format }}
-    SOOS_PROJECT_NAME: ${{ inputs.project_name }}
-    SOOS_TARGET_IMAGE: ${{ inputs.target_image }}
-    SOOS_VERBOSE: ${{ inputs.verbose }}
+  using: "composite"
+  steps:
+    - name: Check version
+      shell: bash
+      env:
+        SOOS_ACTION_REF: ${{ github.action_ref }}
+      run: |
+        set +x  # Turn off command echoing
+        printf '%.0s-' {1..80}
+        printf '\n'
+        response=$(curl -s https://api.github.com/repos/soos-io/soos-csa-github-action/releases/latest)
+        if [ $? -eq 0 ]; then
+          latest_tag=$(echo "$response" | grep -oP '"tag_name": "\K(.*)(?=")')
+          current_tag=$(echo "$SOOS_ACTION_REF" | awk -F'/' '{print $NF}')
+          latest_tag_major=$(echo "$latest_tag" | awk -F'.' '{print $1}')
+          
+          echo "Your current version is: $current_tag, The latest version is: $latest_tag_major"
+          
+          if [[ "$current_tag" != "$latest_tag_major"* ]]; then
+            echo "This action is outdated or using a commit reference. Please update to use the latest major version tag: $latest_tag_major"
+          elif [[ "$current_tag" == "$latest_tag" ]]; then
+            echo "It is recommended to use the major version tag, $latest_tag_major when referencing this action."
+          elif [[ "$current_tag" != "$latest_tag_major" ]]; then
+            echo "This action is out of date. It is recommended to use the major version tag, $latest_tag_major."
+          fi
+        else 
+          echo "Can't check version."
+        fi
+        printf '%.0s-' {1..80}
+        printf '\n'
+
+    - name: Set Arguments
+      shell: bash
+      run: |
+        set +x  # Turn off command echoing
+        args="--integrationName=Github --integrationType=Plugin "
+
+        [[ "${{ inputs.ajax_spider }}" == "true" ]] && args+="--ajaxSpider "
+        [ -n "${{ inputs.api_key }}" ] && args+="--apiKey=${{ inputs.api_key }} "
+        [ -n "${{ inputs.api_scan_format }}" ] && args+="--apiScanFormat=${{ inputs.api_scan_format }} "
+        [ -n "${{ inputs.api_url }}" ] && args+="--apiURL=${{ inputs.api_url }} "
+        [ -n "${{ inputs.branch_name }}" ] && args+="--branchName=${{ inputs.branch_name }} "
+        [ -n "${{ inputs.branch_uri }}" ] && args+="--branchURI=${{ inputs.branch_uri }} "
+        [ -n "${{ inputs.build_uri }}" ] && args+="--buildURI=${{ inputs.build_uri }} "
+        [ -n "${{ inputs.build_version }}" ] && args+="--buildVersion=${{ inputs.build_version }} "
+        [ -n "${{ inputs.client_id }}" ] && args+="--clientId=${{ inputs.client_id }} "
+        [ -n "${{ inputs.log_level }}" ] && args+="--logLevel=${{ inputs.log_level }} "
+        [ -n "${{ inputs.on_failure }}" ] && args+="--onFailure=${{ inputs.on_failure }} "
+        [ -n "${{ inputs.operating_environment }}" ] && args+="--operatingEnvironment=${{ inputs.operating_environment }} "
+        [ -n "${{ inputs.other_options }}" ] && args+="--otherOptions=\"${{ inputs.other_options }}\" "
+        [ -n "${{ inputs.project_name }}" ] && args+="--projectName=\"${{ inputs.project_name }}\" "
+
+        [ -n "${{ inputs.target_image }}" ] && args+="${{ inputs.target_image }}"
+
+        echo "Arguments: $args"
+
+        echo "args=$args" >> $GITHUB_ENV
+
+    - name: Run SOOS Container Scan
+      shell: bash
+      run: |
+        docker pull soosio/csa:${{ inputs.image_tag }}
+        eval "docker run -v ${{ github.workspace }}:/zap/wrk/:rw --rm soosio/csa:${{ inputs.image_tag }} $args"
+
